### ISSUE TITLE
Add ability to decode words without language model context when using w2l

### ISSUE THREAD

**Issue by ckamm** [talonvoice/beta#1]
Currently rules using `<dgndictation>` etc apply a language model to the emissions that is trained on sentences. For some usecases like dictating identifier names (e.g. "@snake word ordering formatter") that's undesired and it would be preferable to not keep language model context between words.

On the dfa level this is already available via the TOKEN_LMWORD vs TOKEN_LMWORD_CTX flag.

Suggestion: Add a new `<standalone_word>`or `<word_no_context>` that makes this behavior available to users.

**Comment by lunixbochs** [comment]
Looks like `<word>` already does this. It compiles to the word token:
```
    token_dict['word'] = 0xff
    token_dict['context_word'] = 0xfe
```
`<word>` compiles to `<word>`
`<phrase>` compiles to `<context_word>+`

**Comment by ckamm** [comment]
Hah, excellent!
