### ISSUE TITLE
[Windows] Incorrect default microphone listed

### ISSUE THREAD

**Issue by knausj85** [talonvoice/beta#101]
My Windows system presently has two devices:
1. Internal Digital Microphone (Apple Audio Device)
2. Andrea Array/stenomask _(default device in control panel)_ 

Upon starting Talon, the _Internal Digital Microphone_ is listed as the default in Talons context menu and activated according to the log. 

But
- I can actually dictate with the Andrea Array as expected (wav2letter). 
- pop/hiss does not work until I explicitly select the Andrea array in the Talon context menu

Talon's the only application I've tested with this issue. (e.g., voice recorder respects the default device)

**Comment by knausj85** [comment]
Also, #19 appears to be back, likely related.

**Comment by lunixbochs** [comment]
hopefully fixed in next release
