### ISSUE TITLE
[Windows] German keyboard layout doesn't print @ symbol

### ISSUE THREAD

**Issue by mathiasringhof** [talonvoice/beta#103]
I'm using the latest beta and knausj's repository with dragon. 

To be able to print the @ symbol I have to:
(1) add `"@": "@"` to keys.py
(2) switch to an american keyboard layout

(1) seems to be related to dragon.

(2) produces the following output on a German keyboard layout: `q`
On my physical keyboard have to press `ALT-Gr q`

I'm seeing similar behavior with \, which is located next to zero on the german keyboard.

**Comment by lunixbochs** [comment]
hopefully fixed in 1467, please confirm

**Comment by mathiasringhof** [comment]
Looks like the new version is pressing ALT instead of ALT-Gr. At least I'm getting the same behavior that the new version of talon is showing if I press ALT-q. But looks like we are close!

**Comment by mathiasringhof** [comment]
1468 fixes the problem for me - thanks for the fast response
