### ISSUE TITLE
Setting.__bool__ should forward to the underlying value

### ISSUE THREAD

**Issue by lslunis** [talonvoice/beta#104]
Right now, settings are always considered true when coerced to bool:

```
if some_setting:
  # always executes
```

It's easy to forget to call .get(), and rather than raising an error, this silently does the wrong thing. Instead, it should either raise an error or behave as if bool(some_setting.get()) was called.

**Comment by lunixbochs** [comment]
should be fixed in 1467, please confirm

**Comment by lslunis** [comment]
Confirmed
