### ISSUE TITLE
[OS X] the menu bar and dock appear over the zoom mouse

### ISSUE THREAD

**Issue by knausj85** [talonvoice/beta#115]
10.15.6

![screenshot-20200914095140](https://user-images.githubusercontent.com/15005956/93108389-f75b9b00-f66f-11ea-9e5f-2b89951edd47.png)

I don't know when this popped up, sadly. I've mostly been on Windows recently.

**Comment by lunixbochs** [comment]
should be fixed in latest beta, please confirm

**Comment by knausj85** [comment]
Issue repro'd on v0.1.2-73 and 10.15.6 here :(

**Comment by lunixbochs** [comment]
Oh, I see command history is on top though. Maybe just something lost in translation with the canvas setup

**Comment by lunixbochs** [comment]
Should be fixed by next beta release. Unfortunately we lose the drop shadow to do so.

**Comment by knausj85** [comment]
No more drop shadow?? `<picard>the line must be drawn here! this far -  no further</picard>` :-D
