### ISSUE TITLE
Jetbrains windows have empty string `.filename`

### ISSUE THREAD

**Issue by dwiel** [talonvoice/beta#117]
Jetbrains windows have empty string for the filename:

```
actions.win.filename()
''
```

I can work around this for file extension detection using `actions.win.title()` for now.

**Comment by dwiel** [comment]
my current workaround:
```
ctx.matches = r"""
app: jetbrains
"""

@ctx.action_class("win")
class win_actions:
    def file_ext():
        return actions.win.title().split(".")[-1]
```

**Comment by lunixbochs** [comment]
This is not a talon bug, it's up to you to polyfill this kind of action in your user scripts for app specific cases exactly as you did here:

https://github.com/knausj85/knausj_talon/search?q=file_ext&unscoped_q=file_ext

**Comment by dwiel** [comment]
Got it, thanks. I had assumed it was a talon action, thanks for the
clarification
