### ISSUE TITLE
<number> doesn't output leading 0s

### ISSUE THREAD

**Issue by dwiel** [talonvoice/beta#124]
```
<number>: insert("{number}")
---
>>> actions.mimic("zero zero one")
{'phrase': ['zero', 'zero', 'one'], 'parsed': C(None, 1)}
1>>> 1
```

**Comment by lunixbochs** [comment]
`<number>` and `<digits>` are statically typed to return an int which can't have leading zeroes, if you want a digits capture named in core talon that returns a string e.g. `<digit_string>` I'm open to suggestions

**Comment by dwiel** [comment]
`<digits_string>` sounds good to me.

**Comment by lunixbochs** [comment]
v0.1.2 has digit_string, (named to avoid a double s)
