### ISSUE TITLE
clip.clear() TypeErrors

### ISSUE THREAD

**Issue by rntz** [talonvoice/beta#132]
Talon v0.1.2-55-g3026bf9 (55)

Ubuntu 20.04.1 LTS

**To reproduce:** open talon repl, run `clip.clear()` or `actions.clip.clear()`:

```
>>> clip.clear()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "talon/clip.py", line 79, in clear
TypeError: 'void(*)(uint32_t)' expects 1 arguments, got 0
```

also occurs if you use clip.clear() in talonscript.

**Comment by lunixbochs** [comment]
fixed in next beta

**Comment by rntz** [comment]
works for me as of talon 73 & 76
