### ISSUE TITLE
[Linux] Middle and right mouse buttons don't work with ctrl.mouse_click()

### ISSUE THREAD

**Issue by aceslowman** [talonvoice/beta#15]
When using the beta on Linux i have had issues triggering middle or right clicks. All clicks, regardless of the `number`, are interpreted as left clicks.

Specifically, I was using the talon_community mouse script, which you can find here:
https://github.com/dwiel/talon_community/blob/master/misc/mouse.py

```
def click(m, button=0, times=1):
    ctrl.mouse_click(button=button, times=times, wait=16000)


def right_click(m):
    click(m, button=1)


def middle_click(m):
    click(m, button=2)
```

Ubuntu 18.04.3 LTS
GNOME

![Screenshot from 2020-01-22 00-09-07](https://user-images.githubusercontent.com/6826702/72872821-7cdaa700-3cab-11ea-87da-4051af04bdbc.png)

**Comment by lunixbochs** [comment]
should be fixed in 8.29-1020, please try and report back

**Comment by aceslowman** [comment]
Just updated to 8.29-1022, when `button` is either 1 or 2, it behaves as a middle click.  Can't seem to produce a right click with other values.

**Comment by lunixbochs** [comment]
Ok, fixed even better in 1023.

>

**Comment by aceslowman** [comment]
Beautiful! Works for me in 1023.
