### ISSUE TITLE
(Windows) Pop noise still triggers when microphone is set to none

### ISSUE THREAD

**Issue by knausj85** [talonvoice/beta#19]
- windows 10
- DPA fine
- version 1025

I do see the following in the log:
2020-02-05 08:15:14  INFO Deactivating Microphone

**Comment by gimpf** [comment]
@lunixbochs This is not only Windows, but also Linux. And not only pop, but also hiss ;-)

```
2020-04-24 09:27:26  INFO Deactivating Microphone
2020-04-24 09:34:11    IO noise hiss active:True
2020-04-24 09:34:11    IO noise hiss active:False
```

Beta Version 1196 on Ubuntu 18.04 LTS.

**Comment by lunixbochs** [comment]
fixed in 1274

**Comment by knausj85** [comment]
This issue appears to be back on Windows (v1426). Unfortunately, I don't know when it re-appeared. 

From what I can tell, "None" appears to be equivalent to the actual system default, and the default listed in talon doesn't necessarily reflect the default in the control panel when there are multiple mics.

My configuration looks like this:
![image](https://user-images.githubusercontent.com/15005956/89468734-5820bb00-d735-11ea-971b-ff0cd768d2da.png)

I can open a new issue if preferred.

**Comment by gimpf** [comment]
Can reproduce in Linux too.
