### ISSUE TITLE
[Windows] If a mic is set to both 

### ISSUE THREAD

**Issue by knausj85** [talonvoice/beta#2]
I have two microphones
1. Internal Microphone (Cirrus Logic)
2. Blue Yeti: Default Device

If either one is set to the default device across the board, the microphone selected at Talon start up is "None," and the Talon context menu fails to load

![defaultDevice](https://user-images.githubusercontent.com/15005956/71146479-43110f00-21da-11ea-80ac-a4c1ab660b8a.PNG)

On the other hand, if one is set as the "Default" and the other is set as "default communication device," Talon selects whichever is set as the default communications device and everything works

**Comment by knausj85** [comment]
[log.txt](https://github.com/talonvoice/beta/files/3981813/log.txt)
Accidentally hit submit. Log attached.

**Comment by lunixbochs** [comment]
is this still an issue?
