### ISSUE TITLE
[Windows] volume_up, volume_down, previous keys don't work

### ISSUE THREAD

**Issue by knausj85** [talonvoice/beta#23]
.talon:

volume up: key(volume_up)
volume down: key(volume_down)
play previous: key(previous)

Works fine on OS X. v1044

Log fwiw -
[sampleLog.txt](https://github.com/talonvoice/beta/files/4221414/sampleLog.txt)

fwiw, windows media key codes from **https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes**
VK_VOLUME_MUTE
0xAD | Volume Mute key
-- | --
VK_VOLUME_DOWN
0xAE | Volume Down key
VK_VOLUME_UP
0xAF | Volume Up key
VK_MEDIA_NEXT_TRACK
0xB0 | Next Track key
VK_MEDIA_PREV_TRACK
0xB1 | Previous Track key
VK_MEDIA_STOP
0xB2 | Stop Media key
VK_MEDIA_PLAY_PAUSE
0xB3 | Play/Pause Media key

**Comment by lunixbochs** [comment]
please change to volup/voldown/prev and test in 1046
