### ISSUE TITLE
Dekstop notifications on Windows

### ISSUE THREAD

**Issue by jcaw** [talonvoice/beta#35]
Some notes discussed on Slack:

https://stackoverflow.com/questions/58096835/qt-windows-10-notifications/58099844#58099844

[win10toast](https://github.com/jithurjacob/Windows-10-Toast-Notifications/blob/master/win10toast/__init__.py)

I had issues with `toast` when I used it, so I switched to `plyer` with Dragonfly.

https://github.com/kivy/plyer

Implementation here:

https://github.com/kivy/plyer/blob/master/plyer/platforms/win/notification.py

**Comment by lunixbochs** [comment]
fixed in 1274
