### ISSUE TITLE
Linux: strip libraries

### ISSUE THREAD

**Issue by zarvox** [talonvoice/beta#41]
`talon/lib/libusb-1.0.so.0` and `talon/lib/libw2l.so` are unstripped in the `talon-linux-89-0.0.8.29-1196-g2d07a86` beta build.

libw2l.so would save about 3 MB (decompressed) if stripped.  libusb-1.0.so.0 would save about 25k.

**Comment by lunixbochs** [comment]
fixed in 1274

unfortunately I had to remove LTO on one of the wav2letter libraries to make it build. so we slightly lost a few more MB than we gained
