### ISSUE TITLE
Mac: Talon presses cmd-letter when the letter is not in the keyboard layout

### ISSUE THREAD

**Issue by JeongJuhyeon** [talonvoice/beta#43]
1. Select a keyboard layout without a certain alphabetic letter (e.g. Korean has none)
2. Attempt to output that letter

Expected: either 1. nothing happens or  (ideally?) 2. the letter is pressed or 3. the symbol that replaces the letter is pressed

What happens: cmd-letter is pressed

**Comment by lunixbochs** [comment]
fixed in 1274
