### ISSUE TITLE
linux gui windows not aligned to monitor

### ISSUE THREAD

**Issue by trapier** [talonvoice/beta#47]
### Issue Summary
Easiest to explain with a picture.  With the following screen layout `show command history` (approximated by orange box) is off screen.

![2020-04-09-232619_517x375_scrot](https://user-images.githubusercontent.com/3613189/78959770-f9ff0680-7ab9-11ea-9c18-7f448e03b2de.png)

Noticed this when I subsequently requested `help alphabet`, and was presented with the bottom half of the resulting GUI window, top center of `DP1-2`. 

### Environment
talon 0.0.8.29-1196-g2d07a86
xorg 1.20.8
i3 4.18

**Comment by trapier** [comment]
per request:
```
>>> ui.screens()
[Screen(x=640.0, y=1784.0, size=(1920.0, 1080.0), mm=(350.0, 190.0)), Screen(x=0.0, y=344.0, size=(2560.0, 1440.0), mm=(530.0, 300.0)), Screen(x=2560.0, y=0.0, size=(1440.0, 2560.0), mm=(340.0, 600.0))]
>>> 
```

**Comment by lunixbochs** [comment]
please retest in 1274

**Comment by trapier** [comment]
Retested on `0.0.8.29-1274-g0b5aa5c`.  Issue remains present. `ui.screens()` tested:

```
>>> ui.screens()
[Screen(x=0.0, y=878.0, size=(3840.0, 2160.0), mm=(600.0, 340.0)), Screen(x=0.0, y=3038.0, size=(3840.0, 2160.0), mm=(350.0, 190.0)), Screen(x=3840.0, y=0.0, size=(2160.0, 3840.0), mm=(300.0, 530.0))]
```

FWIW am still able to test upon request but am no longer regularly impacted by this issue because because I've reconfigured my screens so that the tops of the topmost monitors are aligned.

**Comment by lunixbochs** [comment]
Will be resolved in next beta.
