### ISSUE TITLE
Lexicon problems

### ISSUE THREAD

**Issue by Darksonn** [talonvoice/beta#48]
The purpose of this issue is to collect misspelled words in Talon's dictionary.

 - [ ] implementatiions

**Comment by JeongJuhyeon** [comment]
ter
ena
ina
sigama

**Comment by faithanalog** [comment]
clar

**Comment by bknibbe** [comment]
employe

**Comment by faithanalog** [comment]
ned

**Comment by faithanalog** [comment]
zom

**Comment by lunixbochs** [comment]
Please direct further lexicon suggestions as pull requests to the lexicon repo: https://github.com/talonvoice/lexicon
