### ISSUE TITLE
Linux key input is not reliable when keyboard mapping needs to be changed

### ISSUE THREAD

**Issue by ckamm** [talonvoice/beta#5]
The output for a command that should press "😀😂😇😍😘😚" is frequently wrong. Often one of the emojis is duplicated, replacing another.

Background: To simulate keypresses for keys that are not on the current keyboard mapping talon remaps a keycode to produce the desired keysym. Sometimes this seems to silently not go through. 

One lead is that the keymap change does not seem to arrive in the keymap cache of the python-xlib layer. That may be because the talon code isn't watching for MappingNotify events and forwarding them to the correct function on the Display. That may not be the only issue though.

**Comment by lunixbochs** [comment]
Fixed in beta 884.

My test is inserting the longer emoji string `"😀😂😇😍😘😚😎👍😁👎🤩👉😡🙃🤨😳😱👾"`

Using a long remapped string is necessary to test as there is now a 10 key remap cache, so you need at least 10 consecutive remapped keys to stress the remapper.
