### ISSUE TITLE
imgui DPI weirdness on macOS

### ISSUE THREAD

**Issue by toomanybananas** [talonvoice/beta#50]
I have a retina MBP (running Catalina 10.15.4) and a 27 inch, 1080p monitor (low DPI). When attempting to create an imgui window with `@imgui.open(x=2000, y=800, w=300, h=300)` the window shows up, but the DPI is wrong (font shows up tiny and blurry). Furthermore, the area directly around the window is not clickable, like the click handler thinks the window is bigger but the renderer does not.

**Comment by toomanybananas** [comment]
I managed to fix this by setting my 27 inch monitor as the main monitor in macOS. I'm not sure if that dpi issue will come back on my retina display but I'm happy having all my windows on one display

**Comment by lunixbochs** [comment]
fixed in v0.1.1
