### ISSUE TITLE
frozen cron tasks do not get caught by watchdogs

### ISSUE THREAD

**Issue by faithanalog** [talonvoice/beta#51]
Simple reproduction:

```python
def fn():
    while True: pass

cron.after(‘0s’, fn)
```

Expected: this task eventually gets caught & reported to the log

What actually happens: no watchdog reports are printed

According to slack discussion, this is because watchdogs are implemented _with_ cron, so freezing cron also freezes the watchdogs

**Comment by lunixbochs** [comment]
fixed in next beta release
