### ISSUE TITLE
Notification Tray Icon persists or multiple displayed (windows)

### ISSUE THREAD

**Issue by auphofBSF** [talonvoice/beta#66]
Termination of talon or talon_console, the notification tray icon does not automatically disappear. when talon is restarted 2 or more (if multiple restarts) are often present. Moving mouse over them then reduces the icons to either 1 or none (if Talon not running)

noticed on build 1276, 1299, 1302. (windows10)

**Comment by auphofBSF** [comment]
As discussed in Slack, I can confirm same happens on other applications, agree must be windows bug, 
Windows Version	10.0.18363 Build 18363
Does not appear to have any major ramifications and clears up automatically after cursor is hovered over notification tray

**Comment by lunixbochs** [comment]
I'm going to close as won'tfix, use the talon quit menu item if you want the icon to go away. This is a bug in windows itself imo.
