### ISSUE TITLE
"Mouse control (zoom)" menu unchecked when on internally

### ISSUE THREAD

**Issue by beret** [talonvoice/beta#72]
Build 330 - knausj scripts current as of yesterday, no modifications
Directly connected Tobii 4c on macOS 10.15

### Expected behavior:
Menu accurately reflects toggled state of mouse control (zoom)

### Reproduction:
When I use welcome back/sleep all, mouse.py script sets zoom mouse on (regardless of past state)

Even across a fresh launch of Talon, if I just say welcome back or control mouse, it will also turn on eye control with zoom mouse (I'm using pop to click) but the menu state still shows “control mouse” checked with “control mouse (zoom)” unchecked. I have to toggle "control mouse (zoom)" from the menu (turn explicitly on, then off) to correct behavior.

**Comment by lunixbochs** [comment]
This will be fixed in relation to https://github.com/talonvoice/talon/issues/124 by adding official actions to toggle eye control modes.
