### ISSUE TITLE
List parsing is broken with uppercase lists w/ wav2letter

### ISSUE THREAD

**Issue by jenmei** [talonvoice/beta#88]
List parsing is broken with uppercase lists w/ wav2letter. Example symptom: in [vocabulary.py](https://github.com/knausj85/knausj_talon/blob/7c63d101b073c63d248fd9f19d1b4ce263f2ccff/code/vocabulary.py) in knausj_talon, keys with uppercase letters are causing output like "@dns" instead of "DNS".

**Comment by lunixbochs** [comment]
fixed in 1392
