### ISSUE TITLE
imgui double size and cut off when moving from non-retina to retina on macOS

### ISSUE THREAD

**Issue by nriley** [talonvoice/beta#92]
Some examples:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/68303/88470089-4d109400-cec6-11ea-8ca8-003c2bcf8f19.png">

This only seems to last until the next time the window is updated, for example the next time I dictate something, the command history fixes itself. However, for reference materials such as the alphabet, this is still a problem.

**Comment by nriley** [comment]
The reverse occurs when moving a window back from a retina to a non-retina display:
![image](https://user-images.githubusercontent.com/68303/88470293-bd201980-cec8-11ea-8d2a-e8a60cbe10c5.png)

**Comment by lunixbochs** [comment]
This is when dragging the window with the mouse right?

**Comment by nriley** [comment]
Yes.

**Comment by nriley** [comment]
#50 looks like a similar issue.

**Comment by lunixbochs** [comment]
fixed in v0.1.1

**Comment by nriley** [comment]
Thanks. Confirmed the size issues are resolved — looks like the window contents don't actually redraw so text looks a bit rough on the non-native resolution display, but certainly better than before,
