### ISSUE TITLE
can't relax anchoring of all-mode command in command mode

### ISSUE THREAD

**Issue by rntz** [talonvoice/beta#97]
Consider the following. In one file:

```
mode: all
-
^stupid test$: insert('x')
```

In another file:

```
stupid test$: insert('y')
```

The idea is that I should be able to say "stupid test" all by itself in any mode, but in command mode, I should be allowed to issue commands before it as well. My actual use case for this is switching modes; rather than "stupid test", I want this behavior for "dictation mode".

However, this doesn't seem to work; only the fully anchored version is recognized. So "stupid test" produces "x" as expected, but (in command mode) "word hello stupid test" usually gets recognized as "word hellos" or something else obviously wrong. But if I comment out the all-mode fully anchored command, "word hello stupid test"  starts working. It also suffices to add `mode: command` to the second file, which is the workaround I'm currently using.

**Comment by lunixbochs** [comment]
should be fixed in next talon release (1436)
